public class ElectrophilicNucleophilic : Molecules {
    private List<string> _electrophile = new List<string> {"The oxygen atom in the hydroxyl group can act as a electrophile", "The oxygen atom in the hydroxyl group can act as a electrophile", "The oxygen atom in the hydroxyl group can act as a electrophile", "The oxygen atom in the hydroxyl group can act as a electrophile", "The oxygen atom in the hydroxyl group can act as a electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "The carbonyl carbon can act as an electrophile", "Nitrogen can act as an electrophile, especially if it has an Oxygen atom or another Nitrogen atom at the side", "Nitrogen can act as an electrophile, especially if it has an Oxygen atom or another Nitrogen atom at the side", "Nitrogen can act as an electrophile, especially if it has an Oxygen atom or another Nitrogen atom at the side", "Nitrogen can act as an electrophile, especially if it has an Oxygen atom or another Nitrogen atom at the side", "Nitrogen can act as an electrophile, especially if it has an Oxygen atom or another Nitrogen atom at the side"};
    private List<string> _nucleophile = new List<string> {"The hydroxyl group can also act as a nucleophile in certain reactions", "The hydroxyl group can also act as a nucleophile in certain reactions", "The hydroxyl group can also act as a nucleophile in certain reactions", "The hydroxyl group can also act as a nucleophile in certain reactions", "The hydroxyl group can also act as a nucleophile in certain reactions", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "Aromatic rings can act as both nucleophiles and electrophiles in various reactions, especially in electrophilic aromatic substitution reactions", "The oxygen in the carbonyl group and the hydroxyl group can act as nucleophiles", "The oxygen in the carbonyl group and the hydroxyl group can act as nucleophiles", "The oxygen in the carbonyl group and the hydroxyl group can act as nucleophiles", "The oxygen in the carbonyl group and the hydroxyl group can act as nucleophiles", "The oxygen in the carbonyl group and the hydroxyl group can act as nucleophiles", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The oxygen in the carbonyl group can act as a nucleophile", "The lone pair on nitrogen can act as a nucleophile", "The lone pair on nitrogen can act as a nucleophile", "The lone pair on nitrogen can act as a nucleophile", "The lone pair on nitrogen can act as a nucleophile", "The lone pair on nitrogen can act as a nucleophile"};
    public ElectrophilicNucleophilic() {
        Console.WriteLine(" ");
    }
    public string ShowCharacter(int index) {
        string character = $"Electrophilic Character: {_electrophile[index]}; Nucleophilic Character: {_nucleophile[index]}";
        return character;
    }
}